name: agence_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lazy_loading_list: ^1.0.1
  google_maps_flutter: ^2.1.10
  location: ^4.4.0
  firebase_core: ^1.20.1
  flutter_login: ^4.0.0
  google_sign_in: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/products/
